// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductBacklog.Api.Data.Context;

namespace ProductBacklog.Api.Migrations
{
    [DbContext(typeof(ProductBacklogContext))]
    [Migration("20190212165213_AddDefaultValueToProjectCreatedAt")]
    partial class AddDefaultValueToProjectCreatedAt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductBacklog.Api.Data.Entity.Type.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2019, 2, 12, 14, 52, 12, 939, DateTimeKind.Unspecified).AddTicks(486), new TimeSpan(0, -2, 0, 0, 0)));

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int?>("ParentProjectId");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(1000);

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProductBacklog.Api.Data.Entity.Type.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetailedDescription")
                        .IsRequired();

                    b.Property<int>("ProjectId");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("ProductBacklog.Api.Data.Entity.Type.Project", b =>
                {
                    b.HasOne("ProductBacklog.Api.Data.Entity.Type.Project", "ParentProject")
                        .WithMany("Subprojects")
                        .HasForeignKey("ParentProjectId");
                });

            modelBuilder.Entity("ProductBacklog.Api.Data.Entity.Type.Requirement", b =>
                {
                    b.HasOne("ProductBacklog.Api.Data.Entity.Type.Project", "Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
